[project]
name = "vc_firm"
version = "0.1.0"
description = "vc_firm using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.7"
]

[project.scripts]
vc_firm = "vc_firm.main:run"
run_crew = "vc_firm.main:run"
train = "vc_firm.main:train"
replay = "vc_firm.main:replay"
test = "vc_firm.main:test"
run_with_trigger = "vc_firm.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
